  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#   ----------------------- Deployable Resources  -------------------------   #
#   The following variables are for turning on or off azure resources for     #
#   deployment. If a resource is set to false, it will not deploy, whereas,   #
#   if it is set to true then it will deploy.                                 #
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

variables: 

  # Used to set Log Analytics deployability
  - name: loganalytics
    value: true
  # Used to set Azure SQL Server deployability
  - name: azuresqlserver
    value: true
  # Used to add Control DB to Azure SQL server 
  - name: controldb
    value: true
  # Used to set Blob Storage deployability..
  - name: azureblobstorage
    value: true
  # Used to set Data Lake Storage deployability...
  - name: azuredatalakestorage
    value: true
  # Used to set Databricks Workspace deployability - With Vnet injection
  - name: databricksvnet
    value: true
  # Used to set Databricks Workspace deployability - Deploy NSG.
  - name: databricksvnetnsg
    value: false
  # Used to set DataFactory deployability
  - name: datafactory
    value: true
  # Use to set Synapse Analytics worksspace deployability...
  - name: synapseanalyticsworkspace
    value: true
  # Use to deploy private endpoints
  - name: privateendpoints
    value: false
  # Use to deploy SQL VM for SLT server
  - name: vm_sqlslt
    value: false
  # Use to deploy VM for DevOps Build Agent 
  - name: vm_devops
    value: false
  # Use to deploy VM for ADF Self-Hosted Integration Runtime 
  - name: vm_adfruntime
    value: false
